FROM python:3.9-slim-buster

RUN apt update && \
    apt install -y socat \
    build-essential \
    fonts-dejavu \  
    fonts-liberation \
    && apt-get clean

WORKDIR /chall
COPY source/geneq.py .
COPY source/server.py .
COPY source/genimage.py .
RUN chmod 500 server.py
RUN pip install numpy Pillow z3-solver icecream
EXPOSE 1337
CMD ["socat", "-T10", "TCP-L:1337,fork,reuseaddr", "EXEC:'python3 server.py',pty,stderr,setsid,sane,raw,echo=0"]
